Laboratorio12/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio12.Models
{
    public class Persona
    {
        public int PersonaID { get; set; }
        public string Nombre { get; set; }
        
        public string Apellido { get; set; }

        public  DateTime FechaNac { get; set; }

        public string Direccion { get; set; }
        public string Email { get; set; }

    }
}

Laboratorio12/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Laboratorio12.Models;

namespace Laboratorio12.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {

            return View();

    }

        public ActionResult Listar()
        { 
        List<Persona> personas = new List<Persona>();
        personas.Add(new Persona
            {
                PersonaID =1,
                Nombre = "Alberto",
                Apellido = "Huarcaya",
                Direccion = "Av.Peru Evergrenn 125",
                FechaNac = Convert.ToDateTime("1997-11-08"),
                Email = "albert.huarcaya@tecsup.edu.pe"

            });
            personas.Add(new Persona
            {
                PersonaID = 2,
                Nombre = "Maria",
                Apellido = "huarcaya",
                Direccion = "Av.Peru San Lorenzo 125",
                FechaNac = Convert.ToDateTime("1998-11-05"),
                Email = "maria.huarcaya@tecsup.edu.pe"

            });

            personas.Add(new Persona
            {
                PersonaID = 3,
                Nombre = "Fernanda",
                Apellido = "Salomar",
                Direccion = "Av.Peru Chilina 125",
                FechaNac = Convert.ToDateTime("1998-05-05"),
                Email = "ferna.salo@tecsup.edu.pe"

            });


            return View(personas);
        }

    }
}

Laboratorio12/Views/Persona/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Area Personas</h2>

@Html.ActionLink("Listar personas" , "Listar", "Persona")

Laboratorio12/Views/Persona/Listar.cshtml
@model List<Laboratorio12.Models.Persona>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar Personas Registradas</h2>

<table>
    <tr>
        <th>PersonaID</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Fecha Nacimiento</th>
        <th>Direccion</th>
        <th>Email</th>
    </tr>
    @foreach (var persona in Model)
    {
        <tr>
            <th>@persona.PersonaID</th>
            <th>@persona.Nombre</th>
            <th>@persona.Apellido</th>
            <th>@persona.FechaNac</th>
            <th>@persona.Direccion</th>
            <th>@persona.Email</th>

        </tr>
    }

</table>