Laboratorio9- Tarea/Laboratorio9-Tarea/Models/ViewModels/ArchivoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CursoMVC.Models.ViewModels
{
    public class ArchivoViewModel
    {
        [Required]
        [DisplayName("Mi archivo")]
        public HttpPostedFileBase Archivo1 { get; set; }
        [Required]
        [DisplayName("Mi archivo2")]
        public HttpPostedFileBase Archivo2 { get; set; }
        [Required]
        [DisplayName("Mi cadena")]
        public string Cadena { get; set; }
    }
}

Laboratorio9- Tarea/Laboratorio9-Tarea/Controllers/ArchivoController.cs
using CursoMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CursoMVC.Controllers
{
    public class ArchivoController : Controller
    {
        // GET: Archivo
        public ActionResult Index()
        {
            if (TempData["Message"] != null)
                ViewBag.Message = TempData["Message"].ToString();

            return View();
        }

        [HttpPost]
        public ActionResult Save(ArchivoViewModel model)
        {
            string RutaSitio = Server.MapPath("~/");
            string PathArchivo1 = Path.Combine( RutaSitio+"/Files/archivo1.png" );
            string PathArchivo2 = Path.Combine(RutaSitio + "/Files/archivo2.png");

            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }

            model.Archivo1.SaveAs(PathArchivo1);
            model.Archivo2.SaveAs(PathArchivo2);

            @TempData["Message"] = "Se cargaron los archivos";
            return RedirectToAction("Index");
        }
    }
}

Laboratorio9- Tarea/Laboratorio9-Tarea/Views/Archivo/Index.cshtml
@model CursoMVC.Models.ViewModels.ArchivoViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}

@using (Html.BeginForm("Save","Archivo", FormMethod.Post,
    new {  enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken();
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">
            <div class="form-group">
                @Html.LabelFor(d => d.Archivo1)
                @Html.TextBoxFor(d => d.Archivo1, new { @class = "form-control", type = "file", accept = ".png" })
                @Html.ValidationMessageFor(d => d.Archivo1, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.Archivo2)
                @Html.TextBoxFor(d => d.Archivo2, new { @class = "form-control",type = "file", accept = ".png" })
                @Html.ValidationMessageFor(d => d.Archivo2, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.Cadena)
                @Html.TextBoxFor(d => d.Cadena, new { @class="form-control"})
                @Html.ValidationMessageFor(d => d.Cadena, "", new { @class = "text-danger" })

            </div>
            <div class="form-group" style="text-align:right;" >
                <input type="submit" class="btn btn-success" value="Guardar" >
            </div>
        </div>
    </div>
}